defaults:
  - _self_
  - dataset: mmflood
  - model: vnet
  - loss: 
    - dice_ce_loss
    - kd_loss
    - prototype_loss  


device       : 'cuda'
seed         : 0
num_epochs   : 100
batch_size   : 64
lr           : 1e-3

n_classes    : 2
n_channels   : 2

n_teacher_channels: 3


training_mode: 'distillation'
log_location : ''
teacher_model_path: 'teacher_model.pth'

weights:
  seg: 1
  kd: 0.2
  proto: 0.3
