defaults:
  - _self_
  - dataset: mmflood
  - model: vnet
  # - optimizer: optimizer
  - loss: dice_ce_loss

seed       : 0
num_epochs : 100
batch_size : 64
device     : 'cuda'
training_mode: 'teacher'