defaults:
  - _self_
  - dataset: mmflood
  - model: vnet
  # - optimizer: optimizer
  - loss: dice_ce_loss

seed         : 0
num_epochs   : 100
batch_size   : 64
lr           : 5e-4
device       : 'cuda'
training_mode: 'teacher'
log_location : ''
n_classes    : 2
n_channels   : 3
